// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLEO4FU71-i3vKx4SkDoBAMSpBihCboo',
    appId: '1:342405458075:web:81b74645f52893f4a23e3e',
    messagingSenderId: '342405458075',
    projectId: 'bookingapp-ba769',
    authDomain: 'bookingapp-ba769.firebaseapp.com',
    storageBucket: 'bookingapp-ba769.appspot.com',
    measurementId: 'G-8EMQVNPMCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnBBKuUXVwrU_cF3yUQVMD0pIeIZCmWyA',
    appId: '1:342405458075:android:01204f41e09f595aa23e3e',
    messagingSenderId: '342405458075',
    projectId: 'bookingapp-ba769',
    storageBucket: 'bookingapp-ba769.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV2A_Egz_TE0ZWpZS6VAw6XauUSau1rT0',
    appId: '1:342405458075:ios:67077ddc7bee2eb6a23e3e',
    messagingSenderId: '342405458075',
    projectId: 'bookingapp-ba769',
    storageBucket: 'bookingapp-ba769.appspot.com',
    iosBundleId: 'com.example.bookingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV2A_Egz_TE0ZWpZS6VAw6XauUSau1rT0',
    appId: '1:342405458075:ios:67077ddc7bee2eb6a23e3e',
    messagingSenderId: '342405458075',
    projectId: 'bookingapp-ba769',
    storageBucket: 'bookingapp-ba769.appspot.com',
    iosBundleId: 'com.example.bookingapp',
  );
}
